# Generated by Django 4.2.2 on 2023-06-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_list_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
